### PR TITLE
bump max line length

### PR DESCRIPTION
**Pull request by mjobin-mdsol**
Our code base have so many extremely long lines, 200 chars isn't rare, there are lines that are much longer.
Hitting the 120 target is just never going to happen.

Plus, over the years, GitHub has made it easier to review lines. I remember when 115 was the magic number.
And it got bump a few times.

I find that 145 is a very decent default for our organization

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
Personally I don't think 120 is unachievable, but I don't have any issues with bumping that to 145. My main concern about this point was the visibility on github but now they've expanded the viewport that's ok I guess. I'll still keep my code below 120 chars because it's easier to read (research proved that long lines are indeed harder to read, at least when it comes to essays).

I'd like to get more people to chime in before merging though.

**Comment by mjobin-mdsol** [comment]
I agree it's good to keep it as tidy as possible.

I hope no one writes a large block of 20 lines * 145 chars long code... 
but I find that one long line in a clean code is perfectly fine, and 120 or 145 does not make a difference.

**Comment by mjobin-mdsol** [comment]
For reference, I brought all lines that were above 170 below 145, as a first step for pylon
https://github.com/mdsol/pylon/pull/1184

**Comment by amuntean-mdsol** [comment]
On my 24" monitor (1920 x 1200), on codebases that are limited to 120-char lines, a side-by-side diff on GitHub makes everything fit in very nicely, with no line wraps at all.

With the proposed 145-char lines, the code is wrapping, which makes side-by-side diffing harder. So that is definitely a minus. I agree that writing 145-chars-long lines should be the exception, not the norm 😃  So most lines should not wrap during diffing, while some very long lines will wrap.

Screenshot of the GitHub side-by-side diff, with Chrome fully maximized on my 1920x1200 screen:
Screenshot of the GitHub side-by-side diff, with Chrome fully maximized

@mjobin-mdsol, I am curious, how did you arrive at this magic number: `145`? 😃  It feels a bit arbitrary, but I am sure there's a reason behind it.

**Comment by kjerinsky-mdsol** [comment]
I strive for 80 characters with exceptions such as raw SQL and a hard stop at 120. I find it forces me to break out my code into more variables (in a good way). I'm not a fan of doing too much magic inside of `do` blocks without self-descriptions of what is going on. I'd rather write more functions that are short and compact. When it comes to specs, I don't care as much if I breach 80.

I use a 55" curved 4k television for a monitor with the Wide GitHub extension. Most of the time width doesn't matter but abusing it only ends up hurting more when I'm in the office or on the move without external displays. I know a lot of devs here work exclusively from their notebook display only.  This is why I still prefer to keep widths modest. 

Maybe instead we should be striving to write narrower code?

**Comment by kstephens-medsol** [comment]
allowing longer lines sounds great to me - especially with the whitespace sensitive nature here, and our other indentation style restrictions

**Comment by johnduhart** [comment]
If your code is exceeding 120 chars due to heavy nesting, it's probably way past time to refactor.

120 chars is enough IMO.

**Comment by chchan-mdsol** [comment]
IMO 120 feels like a sweet spot: enough so that the limit doesn't feel absurdly restrictive, but also enough to encourage the dev to be thoughtful about what they're writing.

Or maybe I'm out of touch, and an extra 25 chars couldn't hurt 😅

**Comment by mjobin-mdsol** [comment]
@amuntean-mdsol I seldom use the side-by-side diff. long lines are usually not a problem when I do...

but if that becomes a requirement, we should bring it down to 118, that's what your screenshot shows.

image

**Comment by piao-mdsol** [comment]
I will still enforce 120 chars on to myself, but I'm interested in trying out the new 145 length limit to see how it goes.

> Hitting the 120 target is just never going to happen

If that's one of the main reasons to bump it to 145, then I am not so sure. People who can't follow the 120 chars (for whatever reasons) may still fail the 145 chars IMHO.

**Comment by mjobin-mdsol** [comment]
I try to keep my lines as short as possible. but sometimes it looks nicer with a longer line.
the limit of 120 is really arbitrary. what's good or bad is highly subjective.
the goal is to achieve readable code.

now I read all the comments and most people against the motion is comparing with the ideal world, which is not the world we live in. 

current state of affair is, we cannot enable rubocop on our projects because we have too many offenses. and fixing all the lines to 120 is quite consuming when the most repos have a max set to 350 or ignored entirely.

why 120 was picked is to not scroll on github when viewing a diff (not side by side)

**Comment by ejinotti-mdsol** [comment]
i am probably even more zealous than KJ about a limit of 80.  i find that shorter limits discourage poor/verbose naming and/or trying to do too much in a single line.  i will however, occasionally violate 80 for things like log strings, test descriptions, etc.. but in those cases my absolute max would be 120.

**Comment by ejinotti-mdsol** [comment]
fwiw i also plan to get Dalton to mostly 80 sometime in the not-so-distant future.

**Comment by johnduhart** [comment]
> the limit of 120 is really arbitrary. what's good or bad is highly subjective.
> the goal is to achieve readable code.

Again, I'd argue that a line stretching past 120 characters is not easily readable. Can you provide concrete examples where a longer line is "better"?

> why 120 was picked is to not scroll on github when viewing a diff (not side by side)

That might be why _some_ people want 120, but that's not the only reason.

**Comment by amuntean-mdsol** [comment]
> current state of affair is, we cannot enable rubocop on our projects because we have too many offenses. and fixing all the lines to 120 is quite consuming when the most repos have a max set to 350 or ignored entirely.

@mjobin-mdsol I don't think that's a reason for not enabling Rubocop 😃
For the projects with very long lines, we can disable (or increase) the `LineLength` rule in `.rubocop.yml` or `.rubocop_todo.yml`. The rule can also be disabled/increased per file or per block of code, which is probably better than disabling it per project.

https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration

**Pull request closed without merging**
